### ISSUE TITLE
Integrate in Website

### ISSUE THREAD

**Issue by shrey2199** [dagd/dagd#34]
Is there a way to actually use this in my website ..

**Comment by relrod** [comment]
What is your goal? https://da.gd/help describes the API, and you can send force text mode with `?text` on most endpoints to pull out whatever information you need. In that sense, you can integrate it with your site.

If you're trying to integrate the actual codebase into your pre-existing site, it's not meant to be integrated that way (it's not a library). It's its own framework.

In theory, you could build your own site on top of the framework, but I wouldn't recommend it, there are more powerful and better supported and less specialized frameworks to do that.
