### ISSUE TITLE
Blacklisted long URL (economictimes.indiatimes.com)

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#52]
https://economictimes.indiatimes.com/industry/renewables/indias-power-giant-ntpc-will-turn-to-nuclear-fleet-in-climate-goal-chase/articleshow/96074775.cms

**Comment by relrod** [comment]
This one is from a regex that matches `chase/` due to a phishing attack against Chase bank. I can lift it for now and see what happens; I've not seen reports come in to abuse@ about chase in quite a while.

**Comment by relrod** [comment]
Just FYI you might hit this with a few other patterns. I'm reluctant to just lift them all, even if some of them are a heavy hammer. It's taken quite a while to get things under control (phish scammers love URL shorteners) to the point where our web host and some other parties involved, are happy, and I'd like to keep them happy.

I've lifted the chase pattern that this was hitting for now, though.

**Comment by relrod** [comment]
This functionality already exists in the config. If you want to give me a list of substrings that identify the sites you scrape, I can add them to the whitelist. (It doesn't go by hostname, just substring or regex.)

But I suspect that the users of your library/bot are able to customize the sites that get scraped, so this list will probably vary from user to user.
