### ISSUE TITLE
Morning downtime

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#55]
I have noticed a brief downtime in the mornings for a couple of minutes in a day. I have seen this on multiple days. Is there a process that runs that causes this downtime?

**Comment by phuzion** [comment]
Could you please provide timestamps of when this downtime is occurring, as well as a traceback showing the error your client is experiencing?

**Comment by phuzion** [comment]
Reopening until we can see whether my fix actually, well, fixed the issue.

**Comment by phuzion** [comment]
Anytime. Thanks for the report.
