### ISSUE TITLE
Blacklisted long URL (paypal)

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#56]
- [ ] https://finance.yahoo.com/news/metamask-partners-paypal-ethereum-purchases-031959133.html?.tsrc=rss
- [ ] https://cryptonews.com/news/crypto-adoption-metamask-wallet-teams-up-with-paypal-to-enable-customers-to-buy-eth-directly.htm

**Comment by phuzion** [comment]
If you think that deleting your prior comment from less than 24 hours ago and re-commenting will get you a faster response, you are incorrect.

**Comment by phuzion** [comment]
Correct, however you attempted to bump yourself to the top of our inboxes by deleting your prior comment and re-commenting. I consider this rude and selfish behavior and as a result I will close this issue as there is nothing we can reasonably do to fix your issue without whitelisting domains we will not want to whitelist.

**Comment by phuzion** [comment]
![C1122C4B-56BA-4677-917C-E24F7772ED6F](https://user-images.githubusercontent.com/398094/208214255-15a7ee1c-35bd-4676-ba34-2561ef22fe11.jpeg)

I’m not talking about the comment with the second URL. I’m talking about the comment where you were bumping your issue that was less than a week old.
