### ISSUE TITLE
Blacklisted long URL

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#57]
What's wrong with this URL now...

https://www.lancs.live/news/local-news/disappointment-copeland-misses-out-bid-25186086

If I remind you once a day, it's because I get hammered by repeated errors every 3 to 60 minutes, something that you don't see.

Your blacklist looks to largely be unreasonable. If you no longer provide support, feel free to close out this issue like you did the last one.

**Comment by relrod** [comment]
You do not need to "remind" us. We see the tickets.

```
$ ./scripts/check-blacklist -u 'https://www.lancs.live/news/local-news/disappointment-copeland-misses-out-bid-25186086'
[ERROR] The URL is blacklisted
Blacklist source: shorten.dnsbl [.multi.surbl.org]
```

This URL is in [SURBL](https://en.wikipedia.org/wiki/SURBL)'s "ABUSE" list. I do not know why, perhaps their site was hacked at one point. I would suggest either contacting the site owner or SURBL to see about getting it unlisted.

![image](https://user-images.githubusercontent.com/43930/208822357-67e74fdd-947c-4a4f-bdf9-2f821d5c28b6.png)

> Your blacklist looks to largely be unreasonable.

Okay.
