### ISSUE TITLE
Blacklisted long URL (paypal)

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#59]
I know the string "paypal" is blacklisted, but does the string "-paypal-" also have to be blacklisted? Please think about it. Most news URLs containing the string "paypal" contain it as "-paypal-". For example:

https://www.cnbc.com/2023/01/03/stocks-making-the-biggest-moves-premarket-tesla-coty-paypal-and-more.html

Perhaps a regular expression can be adjusted to avoid blacklisting "-paypal-".

**Comment by relrod** [comment]
I'll try lifting one of the paypal regexes, it'll deploy in a few minutes.
