### ISSUE TITLE
Site is down again

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#66]
The exception is: ConnectTimeout: HTTPSConnectionPool(host='[da.gd](http://da.gd/)', port=443): Max retries exceeded with url: /s (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc17e01ec10>

---

#65 was just two weeks ago. Obviously this is a persistent issue that needs closer investigation.

**Comment by phuzion** [comment]
This is an issue with the upstream provider, and is currently being investigated. This outage has nothing to do with #65.
